## Ex: 1 - Matrix Multiplication

In [1]:
#import library
import numpy as np

In [2]:
A=np.array([[1,2],[3,5]])

In [3]:
B=np.array([[5,6],[7,8]])

In [4]:
C=np.dot(A,B)

In [5]:
print("Matrix A")
print(A)

Matrix A
[[1 2]
 [3 5]]


In [6]:
print("Matrix B")
print(B)

Matrix B
[[5 6]
 [7 8]]


In [7]:
print("Matrix C=A*B")
print(C)

Matrix C=A*B
[[19 22]
 [50 58]]


In [8]:
# sample 2 

a=np.array([[1,2,3],[2,0,1]])
b=np.ones([3,3])
c=np.dot(a,b)
print(a)
print(b)
print(c)

[[1 2 3]
 [2 0 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[6. 6. 6.]
 [3. 3. 3.]]


In [9]:
#sample 3
a=np.array([[2,3],[0,2],[1,2]])
b=np.ones([3,3])
print(a)
print(b)
c=np.dot(a,b)
print(c)

[[2 3]
 [0 2]
 [1 2]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
a=np.array([[1,2,1,1],[2,3,4,5],[7,1,2,3],[1,0,2,0]])
b=np.ones([4,4])
c=a.dot(b)
print(c)

In [ ]:
a=np.array([[2,1],[1,0]])
b=3
c=a*b
print(c)

## EX 2 : Eigen Decomposition

In [ ]:
import numpy as np

In [ ]:
A=np.array([[4,2],[1,3]])

In [ ]:
ev, evector= np.linalg.eig(A)

In [ ]:
print("matrix A")
print(A)

In [ ]:
print("Eigen values")
print(ev)

In [ ]:
print("Eigen vectors")
print(evector)

## Ex 3 Singular Value Decomposition

In [ ]:
import numpy as np

In [ ]:
A=np.array([[3,2,2],[2,3,-2]])

In [ ]:
u,s,v = np.linalg.svd(A)

In [ ]:
print("matrix A")
print(A)

In [ ]:
print("U matrix")
print(u)

In [ ]:
print("singular values")
print(s)

In [ ]:
print("V matrix")
print(v)